# Numpy Tasks

## Task_1

#### Question 1. Create a numpy array with 6X5 2D array from 10 upwards

In [9]:
import numpy as np

my_array = np.arange(10,40)
my_array.shape = (6,5)
print(my_array)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


#### Question 2. From question 1, reshape the numpy array to any shape of your choice and return the max value from each column.

In [10]:
#reshaping the array
new_array = my_array.reshape(3, 10)
print(new_array)

#displaying the max values from each column
print(f"Maximum value = {new_array.max(axis=0)}")

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
Maximum value = [30 31 32 33 34 35 36 37 38 39]


#### Question 3. Create a numpy array A with np.ones with a shape of (3,4). Create another array using the np.arange with a shape of (3,4). 

In [22]:
#creating numpy array with np.ones
A = np.ones((3,4))
print("Array A = \n",A, "\n")

#creating numpy array with np.arange
B = np.arange(2, 25, step=2).reshape(3,4)
print("Array B = \n",B)

Array A = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Array B = 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


#### Question 4. Perform arithmetic operations (+,-,*,/) on the two arrays from question 3.

In [25]:
#Arithmetic operations on array
add = A + B
sub = A - B
mult = A * B
div = A / B

print(f"Addition:\n {add} \n")
print(f"Subtraction:\n {sub}\n")
print(f"Multiplication:\n = {mult}\n")
print(f"Division:\n = {div}")

Addition:
 [[ 3.  5.  7.  9.]
 [11. 13. 15. 17.]
 [19. 21. 23. 25.]] 

Subtraction:
 [[ -1.  -3.  -5.  -7.]
 [ -9. -11. -13. -15.]
 [-17. -19. -21. -23.]]

Multiplication:
 = [[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]]

Division:
 = [[0.5        0.25       0.16666667 0.125     ]
 [0.1        0.08333333 0.07142857 0.0625    ]
 [0.05555556 0.05       0.04545455 0.04166667]]


#### Question 5. From question 4, transpose the results of each arithmetic operation.

In [28]:
print("Addition Transpose: \n", np.transpose(add), "\n")
print("Subtraction Transpose: \n", np.transpose(sub), "\n")
print("Multiplication Transpose: \n", np.transpose(mult), "\n")
print("Division Transpose: \n", np.transpose(div))

Addition Transpose: 
 [[ 3. 11. 19.]
 [ 5. 13. 21.]
 [ 7. 15. 23.]
 [ 9. 17. 25.]] 

Subtraction Transpose: 
 [[ -1.  -9. -17.]
 [ -3. -11. -19.]
 [ -5. -13. -21.]
 [ -7. -15. -23.]] 

Multiplication Transpose: 
 [[ 2. 10. 18.]
 [ 4. 12. 20.]
 [ 6. 14. 22.]
 [ 8. 16. 24.]] 

Division Transpose: 
 [[0.5        0.1        0.05555556]
 [0.25       0.08333333 0.05      ]
 [0.16666667 0.07142857 0.04545455]
 [0.125      0.0625     0.04166667]]
